image: Ubuntu  # образ для сборки

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

build_script:
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации